site_name: swak
copyright: Copyright 2024, Georg Heimel
nav:
  - Home: index.md
  - API Reference:
    - magic: source/magic.md
    - dictionary: source/dictionary.md
    - funcflow: source/funcflow.md
    - text: source/text.md
    - cli: source/cli.md
    - jsonobject: source/jsonobject.md
    - pd: source/pd.md
    - cloud: source/cloud.md
    - pt: source/pt.md
theme:
  name: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            show_root_toc_entry: false
