site_name: swak 
copyright: Copyright 2024, Georg Heimel
nav:
  - Home: index.md
  - API Reference:
    - magic: api/magic.md
    - dictionary: api/dictionary.md
    - funcflow: api/funcflow.md
theme:
  name: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            show_root_toc_entry: false
