name: CI-Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev --frozen

      - name: Run lint
        run: uv run ruff check --verbose

      - name: Run tests
        run: uv run pytest tests
