name: Lint & Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install --upgrade pipenv --user
      - name: Install ruff
        run: pipenv install --dev ruff
      - name: Run ruff
        run: pipenv run ruff check --verbose

  test:
    name: Unittest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install --upgrade pipenv --user
      - name: Sync PyTorch CPU
        run: pipenv sync --categories=cpu
      - name: Install package
        run: pipenv run pip install .[cloud]
      - name: Run unittest
        run: pipenv run python -m unittest
