name: Publishing

on:
#   release:
#     types: [published]
  pull_request:
    branches:
      - featue/add_github_actions/cmayrhofer

jobs:
  publish-package:
    name: publish package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
  deploy-docs:
    needs: publish-package
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Deploy documentation
        run: uv run mkdocs
